// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock_service.go -package=user
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AtomicIncrementFailedAttempts mocks base method.
func (m *MockUserRepository) AtomicIncrementFailedAttempts(ctx context.Context, userID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtomicIncrementFailedAttempts", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AtomicIncrementFailedAttempts indicates an expected call of AtomicIncrementFailedAttempts.
func (mr *MockUserRepositoryMockRecorder) AtomicIncrementFailedAttempts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtomicIncrementFailedAttempts", reflect.TypeOf((*MockUserRepository)(nil).AtomicIncrementFailedAttempts), ctx, userID)
}

// AtomicLockAccount mocks base method.
func (m *MockUserRepository) AtomicLockAccount(ctx context.Context, userID uint, lockedUntil time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtomicLockAccount", ctx, userID, lockedUntil)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AtomicLockAccount indicates an expected call of AtomicLockAccount.
func (mr *MockUserRepositoryMockRecorder) AtomicLockAccount(ctx, userID, lockedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtomicLockAccount", reflect.TypeOf((*MockUserRepository)(nil).AtomicLockAccount), ctx, userID, lockedUntil)
}

// Count mocks base method.
func (m *MockUserRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserRepository)(nil).Count), ctx)
}

// CountByRole mocks base method.
func (m *MockUserRepository) CountByRole(ctx context.Context, role string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByRole", ctx, role)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByRole indicates an expected call of CountByRole.
func (mr *MockUserRepositoryMockRecorder) CountByRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByRole", reflect.TypeOf((*MockUserRepository)(nil).CountByRole), ctx, role)
}

// CountSearch mocks base method.
func (m *MockUserRepository) CountSearch(ctx context.Context, query, role string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSearch", ctx, query, role)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSearch indicates an expected call of CountSearch.
func (mr *MockUserRepositoryMockRecorder) CountSearch(ctx, query, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSearch", reflect.TypeOf((*MockUserRepository)(nil).CountSearch), ctx, query, role)
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// DashboardAuthoredGames mocks base method.
func (m *MockUserRepository) DashboardAuthoredGames(ctx context.Context, userID uint) ([]DashboardGameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DashboardAuthoredGames", ctx, userID)
	ret0, _ := ret[0].([]DashboardGameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DashboardAuthoredGames indicates an expected call of DashboardAuthoredGames.
func (mr *MockUserRepositoryMockRecorder) DashboardAuthoredGames(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DashboardAuthoredGames", reflect.TypeOf((*MockUserRepository)(nil).DashboardAuthoredGames), ctx, userID)
}

// DashboardInvitations mocks base method.
func (m *MockUserRepository) DashboardInvitations(ctx context.Context, userID uint) ([]DashboardInvitationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DashboardInvitations", ctx, userID)
	ret0, _ := ret[0].([]DashboardInvitationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DashboardInvitations indicates an expected call of DashboardInvitations.
func (mr *MockUserRepositoryMockRecorder) DashboardInvitations(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DashboardInvitations", reflect.TypeOf((*MockUserRepository)(nil).DashboardInvitations), ctx, userID)
}

// DashboardTeams mocks base method.
func (m *MockUserRepository) DashboardTeams(ctx context.Context, userID uint) ([]DashboardTeamRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DashboardTeams", ctx, userID)
	ret0, _ := ret[0].([]DashboardTeamRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DashboardTeams indicates an expected call of DashboardTeams.
func (mr *MockUserRepositoryMockRecorder) DashboardTeams(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DashboardTeams", reflect.TypeOf((*MockUserRepository)(nil).DashboardTeams), ctx, userID)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uint) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetByIDWithAchievementsAndSubscriptions mocks base method.
func (m *MockUserRepository) GetByIDWithAchievementsAndSubscriptions(ctx context.Context, id uint) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithAchievementsAndSubscriptions", ctx, id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithAchievementsAndSubscriptions indicates an expected call of GetByIDWithAchievementsAndSubscriptions.
func (mr *MockUserRepositoryMockRecorder) GetByIDWithAchievementsAndSubscriptions(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithAchievementsAndSubscriptions", reflect.TypeOf((*MockUserRepository)(nil).GetByIDWithAchievementsAndSubscriptions), ctx, id)
}

// GetByRole mocks base method.
func (m *MockUserRepository) GetByRole(ctx context.Context, role string) ([]User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRole", ctx, role)
	ret0, _ := ret[0].([]User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRole indicates an expected call of GetByRole.
func (mr *MockUserRepositoryMockRecorder) GetByRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRole", reflect.TypeOf((*MockUserRepository)(nil).GetByRole), ctx, role)
}

// GetGamesView mocks base method.
func (m *MockUserRepository) GetGamesView(ctx context.Context, userID uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGamesView", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGamesView indicates an expected call of GetGamesView.
func (mr *MockUserRepositoryMockRecorder) GetGamesView(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGamesView", reflect.TypeOf((*MockUserRepository)(nil).GetGamesView), ctx, userID)
}

// GetPublicProfile mocks base method.
func (m *MockUserRepository) GetPublicProfile(ctx context.Context, id uint) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicProfile", ctx, id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicProfile indicates an expected call of GetPublicProfile.
func (mr *MockUserRepositoryMockRecorder) GetPublicProfile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicProfile", reflect.TypeOf((*MockUserRepository)(nil).GetPublicProfile), ctx, id)
}

// GetUserRole mocks base method.
func (m *MockUserRepository) GetUserRole(ctx context.Context, id uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockUserRepositoryMockRecorder) GetUserRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockUserRepository)(nil).GetUserRole), ctx, id)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, role string) ([]User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, role)
	ret0, _ := ret[0].([]User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, role)
}

// ListByIDs mocks base method.
func (m *MockUserRepository) ListByIDs(ctx context.Context, ids []uint) ([]User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockUserRepositoryMockRecorder) ListByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockUserRepository)(nil).ListByIDs), ctx, ids)
}

// ListPaginated mocks base method.
func (m *MockUserRepository) ListPaginated(ctx context.Context, role string, offset, limit int) ([]User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaginated", ctx, role, offset, limit)
	ret0, _ := ret[0].([]User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaginated indicates an expected call of ListPaginated.
func (mr *MockUserRepositoryMockRecorder) ListPaginated(ctx, role, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaginated", reflect.TypeOf((*MockUserRepository)(nil).ListPaginated), ctx, role, offset, limit)
}

// SearchPaginated mocks base method.
func (m *MockUserRepository) SearchPaginated(ctx context.Context, query, role string, offset, limit int) ([]User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPaginated", ctx, query, role, offset, limit)
	ret0, _ := ret[0].([]User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPaginated indicates an expected call of SearchPaginated.
func (mr *MockUserRepositoryMockRecorder) SearchPaginated(ctx, query, role, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPaginated", reflect.TypeOf((*MockUserRepository)(nil).SearchPaginated), ctx, query, role, offset, limit)
}

// SearchUsersLight mocks base method.
func (m *MockUserRepository) SearchUsersLight(ctx context.Context, query string, limit int) ([]UserSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersLight", ctx, query, limit)
	ret0, _ := ret[0].([]UserSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersLight indicates an expected call of SearchUsersLight.
func (mr *MockUserRepositoryMockRecorder) SearchUsersLight(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersLight", reflect.TypeOf((*MockUserRepository)(nil).SearchUsersLight), ctx, query, limit)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, id uint, fields map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, id, fields)
}

// MockProfileRepository is a mock of ProfileRepository interface.
type MockProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockProfileRepositoryMockRecorder is the mock recorder for MockProfileRepository.
type MockProfileRepositoryMockRecorder struct {
	mock *MockProfileRepository
}

// NewMockProfileRepository creates a new mock instance.
func NewMockProfileRepository(ctrl *gomock.Controller) *MockProfileRepository {
	mock := &MockProfileRepository{ctrl: ctrl}
	mock.recorder = &MockProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepository) EXPECT() *MockProfileRepositoryMockRecorder {
	return m.recorder
}

// GetGamesView mocks base method.
func (m *MockProfileRepository) GetGamesView(ctx context.Context, userID uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGamesView", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGamesView indicates an expected call of GetGamesView.
func (mr *MockProfileRepositoryMockRecorder) GetGamesView(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGamesView", reflect.TypeOf((*MockProfileRepository)(nil).GetGamesView), ctx, userID)
}

// GetPublicProfileStats mocks base method.
func (m *MockProfileRepository) GetPublicProfileStats(ctx context.Context, userID uint) (*UserStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicProfileStats", ctx, userID)
	ret0, _ := ret[0].(*UserStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicProfileStats indicates an expected call of GetPublicProfileStats.
func (mr *MockProfileRepositoryMockRecorder) GetPublicProfileStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicProfileStats", reflect.TypeOf((*MockProfileRepository)(nil).GetPublicProfileStats), ctx, userID)
}

// GetRecentGames mocks base method.
func (m *MockProfileRepository) GetRecentGames(ctx context.Context, authorID uint) ([]RecentGame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentGames", ctx, authorID)
	ret0, _ := ret[0].([]RecentGame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentGames indicates an expected call of GetRecentGames.
func (mr *MockProfileRepositoryMockRecorder) GetRecentGames(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentGames", reflect.TypeOf((*MockProfileRepository)(nil).GetRecentGames), ctx, authorID)
}

// GetThemeSettings mocks base method.
func (m *MockProfileRepository) GetThemeSettings(ctx context.Context, userID uint) (ThemeSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThemeSettings", ctx, userID)
	ret0, _ := ret[0].(ThemeSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThemeSettings indicates an expected call of GetThemeSettings.
func (mr *MockProfileRepositoryMockRecorder) GetThemeSettings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThemeSettings", reflect.TypeOf((*MockProfileRepository)(nil).GetThemeSettings), ctx, userID)
}

// IsFollowing mocks base method.
func (m *MockProfileRepository) IsFollowing(ctx context.Context, followerID, authorID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", ctx, followerID, authorID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockProfileRepositoryMockRecorder) IsFollowing(ctx, followerID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockProfileRepository)(nil).IsFollowing), ctx, followerID, authorID)
}

// SaveGamesView mocks base method.
func (m *MockProfileRepository) SaveGamesView(ctx context.Context, userID uint, view string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGamesView", ctx, userID, view)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGamesView indicates an expected call of SaveGamesView.
func (mr *MockProfileRepositoryMockRecorder) SaveGamesView(ctx, userID, view any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGamesView", reflect.TypeOf((*MockProfileRepository)(nil).SaveGamesView), ctx, userID, view)
}

// SaveThemeSettings mocks base method.
func (m *MockProfileRepository) SaveThemeSettings(ctx context.Context, userID uint, ts ThemeSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveThemeSettings", ctx, userID, ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveThemeSettings indicates an expected call of SaveThemeSettings.
func (mr *MockProfileRepositoryMockRecorder) SaveThemeSettings(ctx, userID, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveThemeSettings", reflect.TypeOf((*MockProfileRepository)(nil).SaveThemeSettings), ctx, userID, ts)
}

// UpdateProfile mocks base method.
func (m *MockProfileRepository) UpdateProfile(ctx context.Context, userID uint, name, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, name, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileRepositoryMockRecorder) UpdateProfile(ctx, userID, name, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileRepository)(nil).UpdateProfile), ctx, userID, name, email)
}

// MockAchievementRepository is a mock of AchievementRepository interface.
type MockAchievementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAchievementRepositoryMockRecorder
	isgomock struct{}
}

// MockAchievementRepositoryMockRecorder is the mock recorder for MockAchievementRepository.
type MockAchievementRepositoryMockRecorder struct {
	mock *MockAchievementRepository
}

// NewMockAchievementRepository creates a new mock instance.
func NewMockAchievementRepository(ctrl *gomock.Controller) *MockAchievementRepository {
	mock := &MockAchievementRepository{ctrl: ctrl}
	mock.recorder = &MockAchievementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAchievementRepository) EXPECT() *MockAchievementRepositoryMockRecorder {
	return m.recorder
}

// Award mocks base method.
func (m *MockAchievementRepository) Award(ctx context.Context, userID uint, achievement *Achievement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Award", ctx, userID, achievement)
	ret0, _ := ret[0].(error)
	return ret0
}

// Award indicates an expected call of Award.
func (mr *MockAchievementRepositoryMockRecorder) Award(ctx, userID, achievement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Award", reflect.TypeOf((*MockAchievementRepository)(nil).Award), ctx, userID, achievement)
}

// FirstOrCreate mocks base method.
func (m *MockAchievementRepository) FirstOrCreate(ctx context.Context, achievement *Achievement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreate", ctx, achievement)
	ret0, _ := ret[0].(error)
	return ret0
}

// FirstOrCreate indicates an expected call of FirstOrCreate.
func (mr *MockAchievementRepositoryMockRecorder) FirstOrCreate(ctx, achievement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreate", reflect.TypeOf((*MockAchievementRepository)(nil).FirstOrCreate), ctx, achievement)
}

// GetByUserID mocks base method.
func (m *MockAchievementRepository) GetByUserID(ctx context.Context, userID uint) ([]Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockAchievementRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockAchievementRepository)(nil).GetByUserID), ctx, userID)
}

// Seed mocks base method.
func (m *MockAchievementRepository) Seed(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seed", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Seed indicates an expected call of Seed.
func (mr *MockAchievementRepositoryMockRecorder) Seed(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seed", reflect.TypeOf((*MockAchievementRepository)(nil).Seed), ctx)
}

// MockPasswordResetRepository is a mock of PasswordResetRepository interface.
type MockPasswordResetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordResetRepositoryMockRecorder is the mock recorder for MockPasswordResetRepository.
type MockPasswordResetRepositoryMockRecorder struct {
	mock *MockPasswordResetRepository
}

// NewMockPasswordResetRepository creates a new mock instance.
func NewMockPasswordResetRepository(ctrl *gomock.Controller) *MockPasswordResetRepository {
	mock := &MockPasswordResetRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetRepository) EXPECT() *MockPasswordResetRepositoryMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockPasswordResetRepository) CreateToken(ctx context.Context, token *PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockPasswordResetRepositoryMockRecorder) CreateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockPasswordResetRepository)(nil).CreateToken), ctx, token)
}

// DeleteToken mocks base method.
func (m *MockPasswordResetRepository) DeleteToken(ctx context.Context, token *PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockPasswordResetRepositoryMockRecorder) DeleteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockPasswordResetRepository)(nil).DeleteToken), ctx, token)
}

// GetToken mocks base method.
func (m *MockPasswordResetRepository) GetToken(ctx context.Context, tokenStr string) (*PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", ctx, tokenStr)
	ret0, _ := ret[0].(*PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockPasswordResetRepositoryMockRecorder) GetToken(ctx, tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockPasswordResetRepository)(nil).GetToken), ctx, tokenStr)
}

// GetTokenByResetCode mocks base method.
func (m *MockPasswordResetRepository) GetTokenByResetCode(ctx context.Context, code string) (*PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByResetCode", ctx, code)
	ret0, _ := ret[0].(*PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByResetCode indicates an expected call of GetTokenByResetCode.
func (mr *MockPasswordResetRepositoryMockRecorder) GetTokenByResetCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByResetCode", reflect.TypeOf((*MockPasswordResetRepository)(nil).GetTokenByResetCode), ctx, code)
}

// MarkTokenUsed mocks base method.
func (m *MockPasswordResetRepository) MarkTokenUsed(ctx context.Context, id uint, usedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTokenUsed", ctx, id, usedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTokenUsed indicates an expected call of MarkTokenUsed.
func (mr *MockPasswordResetRepositoryMockRecorder) MarkTokenUsed(ctx, id, usedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTokenUsed", reflect.TypeOf((*MockPasswordResetRepository)(nil).MarkTokenUsed), ctx, id, usedAt)
}

// MockEmailVerificationRepository is a mock of EmailVerificationRepository interface.
type MockEmailVerificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailVerificationRepositoryMockRecorder is the mock recorder for MockEmailVerificationRepository.
type MockEmailVerificationRepositoryMockRecorder struct {
	mock *MockEmailVerificationRepository
}

// NewMockEmailVerificationRepository creates a new mock instance.
func NewMockEmailVerificationRepository(ctrl *gomock.Controller) *MockEmailVerificationRepository {
	mock := &MockEmailVerificationRepository{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationRepository) EXPECT() *MockEmailVerificationRepositoryMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockEmailVerificationRepository) CreateToken(ctx context.Context, token *EmailVerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockEmailVerificationRepositoryMockRecorder) CreateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockEmailVerificationRepository)(nil).CreateToken), ctx, token)
}

// DeleteByTokenHash mocks base method.
func (m *MockEmailVerificationRepository) DeleteByTokenHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTokenHash indicates an expected call of DeleteByTokenHash.
func (mr *MockEmailVerificationRepositoryMockRecorder) DeleteByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTokenHash", reflect.TypeOf((*MockEmailVerificationRepository)(nil).DeleteByTokenHash), ctx, tokenHash)
}

// DeleteByUserID mocks base method.
func (m *MockEmailVerificationRepository) DeleteByUserID(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockEmailVerificationRepositoryMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockEmailVerificationRepository)(nil).DeleteByUserID), ctx, userID)
}

// DeleteToken mocks base method.
func (m *MockEmailVerificationRepository) DeleteToken(ctx context.Context, token *EmailVerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockEmailVerificationRepositoryMockRecorder) DeleteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockEmailVerificationRepository)(nil).DeleteToken), ctx, token)
}

// GetToken mocks base method.
func (m *MockEmailVerificationRepository) GetToken(ctx context.Context, tokenStr string) (*EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", ctx, tokenStr)
	ret0, _ := ret[0].(*EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockEmailVerificationRepositoryMockRecorder) GetToken(ctx, tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockEmailVerificationRepository)(nil).GetToken), ctx, tokenStr)
}

// GetTokenByCode mocks base method.
func (m *MockEmailVerificationRepository) GetTokenByCode(ctx context.Context, code string) (*EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByCode", ctx, code)
	ret0, _ := ret[0].(*EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByCode indicates an expected call of GetTokenByCode.
func (mr *MockEmailVerificationRepositoryMockRecorder) GetTokenByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByCode", reflect.TypeOf((*MockEmailVerificationRepository)(nil).GetTokenByCode), ctx, code)
}

// MockExternalLoginRepository is a mock of ExternalLoginRepository interface.
type MockExternalLoginRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExternalLoginRepositoryMockRecorder
	isgomock struct{}
}

// MockExternalLoginRepositoryMockRecorder is the mock recorder for MockExternalLoginRepository.
type MockExternalLoginRepositoryMockRecorder struct {
	mock *MockExternalLoginRepository
}

// NewMockExternalLoginRepository creates a new mock instance.
func NewMockExternalLoginRepository(ctrl *gomock.Controller) *MockExternalLoginRepository {
	mock := &MockExternalLoginRepository{ctrl: ctrl}
	mock.recorder = &MockExternalLoginRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalLoginRepository) EXPECT() *MockExternalLoginRepositoryMockRecorder {
	return m.recorder
}

// ExistsByProviderExternalIDForUser mocks base method.
func (m *MockExternalLoginRepository) ExistsByProviderExternalIDForUser(ctx context.Context, provider, externalID string, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByProviderExternalIDForUser", ctx, provider, externalID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByProviderExternalIDForUser indicates an expected call of ExistsByProviderExternalIDForUser.
func (mr *MockExternalLoginRepositoryMockRecorder) ExistsByProviderExternalIDForUser(ctx, provider, externalID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByProviderExternalIDForUser", reflect.TypeOf((*MockExternalLoginRepository)(nil).ExistsByProviderExternalIDForUser), ctx, provider, externalID, userID)
}

// FindOrCreate mocks base method.
func (m *MockExternalLoginRepository) FindOrCreate(ctx context.Context, login *ExternalLogin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockExternalLoginRepositoryMockRecorder) FindOrCreate(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockExternalLoginRepository)(nil).FindOrCreate), ctx, login)
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// ClaimAndCreate mocks base method.
func (m *MockRefreshTokenRepository) ClaimAndCreate(ctx context.Context, id uint, newToken *RefreshToken) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimAndCreate", ctx, id, newToken)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimAndCreate indicates an expected call of ClaimAndCreate.
func (mr *MockRefreshTokenRepositoryMockRecorder) ClaimAndCreate(ctx, id, newToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimAndCreate", reflect.TypeOf((*MockRefreshTokenRepository)(nil).ClaimAndCreate), ctx, id, newToken)
}

// ClaimForRefresh mocks base method.
func (m *MockRefreshTokenRepository) ClaimForRefresh(ctx context.Context, id uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimForRefresh", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimForRefresh indicates an expected call of ClaimForRefresh.
func (mr *MockRefreshTokenRepositoryMockRecorder) ClaimForRefresh(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimForRefresh", reflect.TypeOf((*MockRefreshTokenRepository)(nil).ClaimForRefresh), ctx, id)
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, token *RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, token)
}

// DeleteExpired mocks base method.
func (m *MockRefreshTokenRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteExpired), ctx)
}

// GetByTokenHash mocks base method.
func (m *MockRefreshTokenRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).GetByTokenHash), ctx, tokenHash)
}

// GetByTokenHashIncludingRevoked mocks base method.
func (m *MockRefreshTokenRepository) GetByTokenHashIncludingRevoked(ctx context.Context, tokenHash string) (*RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHashIncludingRevoked", ctx, tokenHash)
	ret0, _ := ret[0].(*RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHashIncludingRevoked indicates an expected call of GetByTokenHashIncludingRevoked.
func (mr *MockRefreshTokenRepositoryMockRecorder) GetByTokenHashIncludingRevoked(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHashIncludingRevoked", reflect.TypeOf((*MockRefreshTokenRepository)(nil).GetByTokenHashIncludingRevoked), ctx, tokenHash)
}

// Revoke mocks base method.
func (m *MockRefreshTokenRepository) Revoke(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenRepositoryMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Revoke), ctx, id)
}

// RevokeAllByFamily mocks base method.
func (m *MockRefreshTokenRepository) RevokeAllByFamily(ctx context.Context, familyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllByFamily", ctx, familyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllByFamily indicates an expected call of RevokeAllByFamily.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeAllByFamily(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllByFamily", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeAllByFamily), ctx, familyID)
}

// RevokeAllForUser mocks base method.
func (m *MockRefreshTokenRepository) RevokeAllForUser(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeAllForUser), ctx, userID)
}

// MockPushSubscriptionRepository is a mock of PushSubscriptionRepository interface.
type MockPushSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPushSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockPushSubscriptionRepositoryMockRecorder is the mock recorder for MockPushSubscriptionRepository.
type MockPushSubscriptionRepositoryMockRecorder struct {
	mock *MockPushSubscriptionRepository
}

// NewMockPushSubscriptionRepository creates a new mock instance.
func NewMockPushSubscriptionRepository(ctrl *gomock.Controller) *MockPushSubscriptionRepository {
	mock := &MockPushSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockPushSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSubscriptionRepository) EXPECT() *MockPushSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPushSubscriptionRepository) Create(ctx context.Context, sub *PushSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPushSubscriptionRepositoryMockRecorder) Create(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).Create), ctx, sub)
}

// DeleteByEndpointAndUser mocks base method.
func (m *MockPushSubscriptionRepository) DeleteByEndpointAndUser(ctx context.Context, endpoint string, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEndpointAndUser", ctx, endpoint, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEndpointAndUser indicates an expected call of DeleteByEndpointAndUser.
func (mr *MockPushSubscriptionRepositoryMockRecorder) DeleteByEndpointAndUser(ctx, endpoint, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEndpointAndUser", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).DeleteByEndpointAndUser), ctx, endpoint, userID)
}

// FindByEndpoint mocks base method.
func (m *MockPushSubscriptionRepository) FindByEndpoint(ctx context.Context, endpoint string) (*PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEndpoint", ctx, endpoint)
	ret0, _ := ret[0].(*PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEndpoint indicates an expected call of FindByEndpoint.
func (mr *MockPushSubscriptionRepositoryMockRecorder) FindByEndpoint(ctx, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEndpoint", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).FindByEndpoint), ctx, endpoint)
}

// Update mocks base method.
func (m *MockPushSubscriptionRepository) Update(ctx context.Context, sub *PushSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPushSubscriptionRepositoryMockRecorder) Update(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).Update), ctx, sub)
}
