// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"gengine-0/internal/config"
	"gengine-0/internal/domain/admin"
	"gengine-0/internal/domain/export"
	"gengine-0/internal/domain/game"
	"gengine-0/internal/domain/level"
	"gengine-0/internal/domain/monitor"
	"gengine-0/internal/domain/notification"
	"gengine-0/internal/domain/social"
	"gengine-0/internal/domain/team"
	"gengine-0/internal/domain/tournament"
	"gengine-0/internal/domain/user"
	"gengine-0/internal/pkg/cache"
	"gengine-0/internal/pkg/storage"
	"gengine-0/internal/pkg/websocket"
	"gorm.io/gorm"
)

import (
	_ "gengine-0/docs"
)

// Injectors from wire.go:

func initializeRepositories(db *gorm.DB) *repositories {
	userRepository := user.NewGormUserRepo(db)
	achievementRepository := user.NewGormAchievementRepo(db)
	passwordResetRepository := user.NewGormPasswordResetRepo(db)
	emailVerificationRepository := user.NewGormEmailVerificationRepo(db)
	externalLoginRepository := user.NewGormExternalLoginRepo(db)
	refreshTokenRepository := user.NewGormRefreshTokenRepo(db)
	webAuthnRepository := user.NewGormWebAuthnRepo(db)
	pushSubscriptionRepository := user.NewGormPushSubscriptionRepo(db)
	gameRepository := game.NewGormGameRepo(db)
	gamePassingRepository := game.NewGormGamePassingRepo(db)
	levelProgressRepository := game.NewGormLevelProgressRepo(db)
	noteRepository := game.NewGormNoteRepo(db)
	photoRepository := game.NewGormPhotoRepo(db)
	reviewRepository := game.NewGormReviewRepo(db)
	ratingRepository := game.NewGormRatingRepo(db)
	coAuthorRepository := game.NewGormCoAuthorRepo(db)
	monitorRepository := game.NewGormMonitorRepo(db)
	levelRepository := level.NewGormLevelRepo(db)
	questionRepository := level.NewGormQuestionRepo(db)
	answerRepository := level.NewGormAnswerRepo(db)
	teamRepository := team.NewGormTeamRepo(db)
	invitationRepository := team.NewGormInvitationRepo(db)
	tournamentRepository := tournament.NewGormTournamentRepo(db)
	tournamentGameRepository := tournament.NewGormTournamentGameRepo(db)
	tournamentTeamRepository := tournament.NewGormTournamentTeamRepo(db)
	tournamentResultRepository := tournament.NewGormTournamentResultRepo(db)
	followRepository := social.NewGormFollowRepo(db)
	exportRepository := export.NewGormExportRepo(db)
	chatRepository := monitor.NewGormChatRepo(db)
	blackboxRepository := monitor.NewGormBlackboxRepo(db)
	notificationRepository := notification.NewNotificationRepository(db)
	backupRepository := admin.NewGormBackupRepo(db)
	appRepositories := &repositories{
		User:          userRepository,
		Achiev:        achievementRepository,
		PassReset:     passwordResetRepository,
		EmailVerif:    emailVerificationRepository,
		ExtLogin:      externalLoginRepository,
		RefreshToken:  refreshTokenRepository,
		WebAuthn:      webAuthnRepository,
		PushSub:       pushSubscriptionRepository,
		Game:          gameRepository,
		GamePassing:   gamePassingRepository,
		LevelProgress: levelProgressRepository,
		Note:          noteRepository,
		Photo:         photoRepository,
		Review:        reviewRepository,
		Rating:        ratingRepository,
		CoAuthor:      coAuthorRepository,
		Monitor:       monitorRepository,
		Level:         levelRepository,
		Question:      questionRepository,
		Answer:        answerRepository,
		Team:          teamRepository,
		Invitation:    invitationRepository,
		Tournament:    tournamentRepository,
		TournGame:     tournamentGameRepository,
		TournTeam:     tournamentTeamRepository,
		TournResult:   tournamentResultRepository,
		Follow:        followRepository,
		Export:        exportRepository,
		Chat:          chatRepository,
		Blackbox:      blackboxRepository,
		Notification:  notificationRepository,
		Backup:        backupRepository,
	}
	return appRepositories
}

func initializeServices(db *gorm.DB, repos *repositories, cfg *config.Config, hub *websocket.RoomHub, localStorage storage.FileStorage, appCache cache.CacheStore) (*services, error) {
	userRepository := repos.User
	achievementRepository := repos.Achiev
	emailVerificationRepository := repos.EmailVerif
	refreshTokenRepository := repos.RefreshToken
	emailVerificationService := wrapEmailVerificationService(userRepository, emailVerificationRepository, cfg)
	authService := wrapAuthService(userRepository, achievementRepository, emailVerificationRepository, refreshTokenRepository, cfg, appCache, emailVerificationService)
	refreshTokenService := wrapRefreshTokenService(refreshTokenRepository, userRepository, cfg, authService)
	userService := wrapUserService(userRepository)
	achievementService := wrapAchievementService(achievementRepository)
	externalLoginRepository := repos.ExtLogin
	oAuthService := wrapOAuthService(userRepository, externalLoginRepository, cfg)
	passwordResetRepository := repos.PassReset
	passwordResetService := wrapPasswordResetService(userRepository, passwordResetRepository, cfg)
	emailService := wrapEmailService(cfg, db)
	twoFactorService := wrapTwoFactorService()
	gameRepository := repos.Game
	gamePassingRepository := repos.GamePassing
	coAuthorRepository := repos.CoAuthor
	coAuthorService := wrapCoAuthorService(db, coAuthorRepository)
	reviewRepository := repos.Review
	reviewService := wrapReviewService(reviewRepository, appCache)
	monitorRepository := repos.Monitor
	monitorService := wrapMonitorService(db, monitorRepository)
	photoRepository := repos.Photo
	photoService := wrapPhotoService(photoRepository, coAuthorRepository)
	ratingRepository := repos.Rating
	ratingService := wrapRatingService(db, ratingRepository, appCache)
	gameService := wrapGameService(gameRepository, gamePassingRepository, coAuthorService, reviewService, monitorService, photoService, hub, cfg, localStorage, appCache, userRepository, ratingService)
	attemptService := game.NewAttemptService()
	sseManager := game.NewSSEManager()
	gamePlayService := wrapGamePlayService(db, gameRepository, gamePassingRepository, attemptService, monitorService, hub, coAuthorService, sseManager)
	teamRepository := repos.Team
	gameAdminService := wrapGameAdminService(db, teamRepository, userRepository, coAuthorService, cfg, sseManager)
	teamService := wrapTeamService(teamRepository)
	levelProgressRepository := repos.LevelProgress
	levelProgressService := wrapLevelProgressService(db, levelProgressRepository, sseManager, gameService)
	gamePassingService := wrapGamePassingService(db, gamePassingRepository, teamService, coAuthorService, levelProgressService, hub, monitorService, sseManager)
	gameplayHandler := wrapGameplayHandler(gameService, gamePlayService, attemptService, levelProgressService, monitorService, hub, localStorage)
	noteRepository := repos.Note
	noteService := wrapNoteService(noteRepository, coAuthorService)
	simulateService := wrapSimulateService(gameRepository, coAuthorService)
	levelRepository := repos.Level
	questionRepository := repos.Question
	answerRepository := repos.Answer
	levelService := wrapLevelService(levelRepository, questionRepository, answerRepository, coAuthorService, gameAdminService)
	questionService := wrapQuestionService(questionRepository, levelRepository, coAuthorService)
	answerService := wrapAnswerService(answerRepository, questionRepository, levelRepository, coAuthorService)
	invitationRepository := repos.Invitation
	invitationService := wrapInvitationService(invitationRepository, teamRepository, cfg)
	tournamentRepository := repos.Tournament
	tournamentGameRepository := repos.TournGame
	tournamentTeamRepository := repos.TournTeam
	tournamentResultRepository := repos.TournResult
	tournamentService := wrapTournamentService(db, tournamentRepository, tournamentGameRepository, tournamentTeamRepository, tournamentResultRepository, teamService, cfg, appCache)
	notificationRepository := repos.Notification
	notificationService := wrapNotificationService(notificationRepository, hub, sseManager, cfg)
	exportRepository := repos.Export
	exportService, err := wrapExportService(exportRepository, db)
	if err != nil {
		return nil, err
	}
	followRepository := repos.Follow
	followService := wrapFollowService(followRepository)
	chatRepository := repos.Chat
	chatService := wrapChatService(chatRepository)
	blackboxRepository := repos.Blackbox
	blackboxVoteService := wrapBlackboxVoteService(blackboxRepository, coAuthorService, db, cfg)
	backupRepository := repos.Backup
	backupService := wrapBackupService(backupRepository, cfg)
	calendarHandler := wrapCalendarHandler(gameRepository, cfg)
	pushSubscriptionRepository := repos.PushSub
	pushHandler := wrapPushHandler(pushSubscriptionRepository, cfg)
	profileService := wrapProfileService(db)
	userDashboardService := wrapUserDashboardService(userRepository)
	appServices := &services{
		Auth:            authService,
		RefreshToken:    refreshTokenService,
		User:            userService,
		Achiev:          achievementService,
		OAuth:           oAuthService,
		PasswordReset:   passwordResetService,
		EmailVerif:      emailVerificationService,
		Email:           emailService,
		TwoFactor:       twoFactorService,
		Game:            gameService,
		GamePlay:        gamePlayService,
		GameAdmin:       gameAdminService,
		GamePassing:     gamePassingService,
		GameplayHandler: gameplayHandler,
		CoAuthor:        coAuthorService,
		Review:          reviewService,
		Note:            noteService,
		PhotoService:    photoService,
		Attempt:         attemptService,
		Progress:        levelProgressService,
		Monitor:         monitorService,
		Rating:          ratingService,
		Simulate:        simulateService,
		SSEMgr:          sseManager,
		Level:           levelService,
		Question:        questionService,
		Answer:          answerService,
		Team:            teamService,
		Invitation:      invitationService,
		Tournament:      tournamentService,
		Notification:    notificationService,
		Export:          exportService,
		Follow:          followService,
		Chat:            chatService,
		BlackboxVote:    blackboxVoteService,
		Backup:          backupService,
		CalendarHandler: calendarHandler,
		PushHandler:     pushHandler,
		Profile:         profileService,
		UserDashboard:   userDashboardService,
	}
	return appServices, nil
}
