// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"gengine-0/internal/config"
	"gengine-0/internal/domain/game"
	"gengine-0/internal/domain/level"
	"gengine-0/internal/domain/team"
	"gengine-0/internal/domain/tournament"
	"gengine-0/internal/domain/user"
	"gengine-0/internal/pkg/cache"
	"gengine-0/internal/pkg/storage"
	"gengine-0/internal/pkg/websocket"
	"gorm.io/gorm"
)

import (
	_ "gengine-0/docs"
)

// Injectors from wire.go:

func initializeRepositories(db *gorm.DB) *repositories {
	userRepository := user.NewGormUserRepo(db)
	achievementRepository := user.NewGormAchievementRepo(db)
	passwordResetRepository := user.NewGormPasswordResetRepo(db)
	emailVerificationRepository := user.NewGormEmailVerificationRepo(db)
	externalLoginRepository := user.NewGormExternalLoginRepo(db)
	refreshTokenRepository := user.NewGormRefreshTokenRepo(db)
	webAuthnRepository := user.NewGormWebAuthnRepo(db)
	gameRepository := game.NewGormGameRepo(db)
	gamePassingRepository := game.NewGormGamePassingRepo(db)
	levelRepository := level.NewGormLevelRepo(db)
	questionRepository := level.NewGormQuestionRepo(db)
	answerRepository := level.NewGormAnswerRepo(db)
	teamRepository := team.NewGormTeamRepo(db)
	invitationRepository := team.NewGormInvitationRepo(db)
	tournamentRepository := tournament.NewGormTournamentRepo(db)
	tournamentGameRepository := tournament.NewGormTournamentGameRepo(db)
	tournamentTeamRepository := tournament.NewGormTournamentTeamRepo(db)
	tournamentResultRepository := tournament.NewGormTournamentResultRepo(db)
	appRepositories := &repositories{
		User:         userRepository,
		Achiev:       achievementRepository,
		PassReset:    passwordResetRepository,
		EmailVerif:   emailVerificationRepository,
		ExtLogin:     externalLoginRepository,
		RefreshToken: refreshTokenRepository,
		WebAuthn:     webAuthnRepository,
		Game:         gameRepository,
		GamePassing:  gamePassingRepository,
		Level:        levelRepository,
		Question:     questionRepository,
		Answer:       answerRepository,
		Team:         teamRepository,
		Invitation:   invitationRepository,
		Tournament:   tournamentRepository,
		TournGame:    tournamentGameRepository,
		TournTeam:    tournamentTeamRepository,
		TournResult:  tournamentResultRepository,
	}
	return appRepositories
}

func initializeServices(db *gorm.DB, repos *repositories, cfg *config.Config, hub *websocket.RoomHub, localStorage storage.FileStorage, appCache cache.CacheStore) *services {
	userRepository := repos.User
	achievementRepository := repos.Achiev
	emailVerificationRepository := repos.EmailVerif
	refreshTokenRepository := repos.RefreshToken
	authService := wrapAuthService(userRepository, achievementRepository, emailVerificationRepository, refreshTokenRepository, cfg)
	userService := wrapUserService(userRepository)
	achievementService := wrapAchievementService(achievementRepository)
	externalLoginRepository := repos.ExtLogin
	oAuthService := wrapOAuthService(userRepository, externalLoginRepository, cfg)
	passwordResetRepository := repos.PassReset
	passwordResetService := wrapPasswordResetService(userRepository, passwordResetRepository, cfg)
	emailVerificationService := wrapEmailVerificationService(userRepository, emailVerificationRepository, cfg)
	emailService := wrapEmailService(cfg, db)
	gameRepository := repos.Game
	gamePassingRepository := repos.GamePassing
	coAuthorService := game.NewCoAuthorService(db)
	reviewService := game.NewReviewService(db)
	monitorService := game.NewMonitorService(db)
	photoService := game.NewPhotoService(db)
	ratingService := game.NewRatingService(db, appCache)
	gameService := wrapGameService(db, gameRepository, gamePassingRepository, coAuthorService, reviewService, monitorService, photoService, hub, cfg, localStorage, appCache, userRepository, ratingService)
	attemptService := game.NewAttemptService(db)
	sseManager := game.NewSSEManager()
	levelProgressService := wrapLevelProgressService(db, sseManager, gameService)
	gamePlayService := wrapGamePlayService(db, attemptService, levelProgressService, monitorService, hub, coAuthorService, cfg, sseManager)
	gameAdminService := wrapGameAdminService(db, coAuthorService, cfg, sseManager)
	gameplayHandler := wrapGameplayHandler(gameService, gamePlayService, attemptService, levelProgressService, monitorService, hub, localStorage)
	levelRepository := repos.Level
	questionRepository := repos.Question
	answerRepository := repos.Answer
	levelService := wrapLevelService(levelRepository, questionRepository, answerRepository, coAuthorService, gameAdminService)
	questionService := wrapQuestionService(questionRepository, levelRepository, coAuthorService)
	answerService := wrapAnswerService(answerRepository, questionRepository, levelRepository, coAuthorService)
	teamRepository := repos.Team
	teamService := wrapTeamService(teamRepository, coAuthorService)
	invitationRepository := repos.Invitation
	invitationService := wrapInvitationService(invitationRepository, teamRepository, coAuthorService, cfg)
	tournamentRepository := repos.Tournament
	tournamentGameRepository := repos.TournGame
	tournamentTeamRepository := repos.TournTeam
	tournamentResultRepository := repos.TournResult
	tournamentService := wrapTournamentService(tournamentRepository, tournamentGameRepository, tournamentTeamRepository, tournamentResultRepository, teamService, cfg)
	appServices := &services{
		Auth:            authService,
		User:            userService,
		Achiev:          achievementService,
		OAuth:           oAuthService,
		PasswordReset:   passwordResetService,
		EmailVerif:      emailVerificationService,
		Email:           emailService,
		Game:            gameService,
		GamePlay:        gamePlayService,
		GameAdmin:       gameAdminService,
		GameplayHandler: gameplayHandler,
		CoAuthor:        coAuthorService,
		Review:          reviewService,
		PhotoService:    photoService,
		Attempt:         attemptService,
		Progress:        levelProgressService,
		Monitor:         monitorService,
		Rating:          ratingService,
		SSEMgr:          sseManager,
		Level:           levelService,
		Question:        questionService,
		Answer:          answerService,
		Team:            teamService,
		Invitation:      invitationService,
		Tournament:      tournamentService,
	}
	return appServices
}
