// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\PC_User\Desktop\Gengine-0\internal\domain\game\repository.go
//
// Generated by this command:
//
//	mockgen -source=C:\Users\PC_User\Desktop\Gengine-0\internal\domain\game\repository.go -destination=C:\Users\PC_User\Desktop\Gengine-0\internal\domain\game\mock_repository.go -package=game
//

// Package game is a generated GoMock package.
package game

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockGameRepository is a mock of GameRepository interface.
type MockGameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameRepositoryMockRecorder
	isgomock struct{}
}

// MockGameRepositoryMockRecorder is the mock recorder for MockGameRepository.
type MockGameRepositoryMockRecorder struct {
	mock *MockGameRepository
}

// NewMockGameRepository creates a new mock instance.
func NewMockGameRepository(ctrl *gomock.Controller) *MockGameRepository {
	mock := &MockGameRepository{ctrl: ctrl}
	mock.recorder = &MockGameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameRepository) EXPECT() *MockGameRepositoryMockRecorder {
	return m.recorder
}

// AdminListGames mocks base method.
func (m *MockGameRepository) AdminListGames(ctx context.Context, query, status string, offset, limit int) ([]Game, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListGames", ctx, query, status, offset, limit)
	ret0, _ := ret[0].([]Game)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AdminListGames indicates an expected call of AdminListGames.
func (mr *MockGameRepositoryMockRecorder) AdminListGames(ctx, query, status, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListGames", reflect.TypeOf((*MockGameRepository)(nil).AdminListGames), ctx, query, status, offset, limit)
}

// CountActivePassings mocks base method.
func (m *MockGameRepository) CountActivePassings(ctx context.Context, gameID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActivePassings", ctx, gameID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActivePassings indicates an expected call of CountActivePassings.
func (mr *MockGameRepositoryMockRecorder) CountActivePassings(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActivePassings", reflect.TypeOf((*MockGameRepository)(nil).CountActivePassings), ctx, gameID)
}

// CountLevelsByGame mocks base method.
func (m *MockGameRepository) CountLevelsByGame(ctx context.Context, gameID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLevelsByGame", ctx, gameID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLevelsByGame indicates an expected call of CountLevelsByGame.
func (mr *MockGameRepositoryMockRecorder) CountLevelsByGame(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLevelsByGame", reflect.TypeOf((*MockGameRepository)(nil).CountLevelsByGame), ctx, gameID)
}

// CountPublished mocks base method.
func (m *MockGameRepository) CountPublished(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPublished", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPublished indicates an expected call of CountPublished.
func (mr *MockGameRepositoryMockRecorder) CountPublished(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPublished", reflect.TypeOf((*MockGameRepository)(nil).CountPublished), ctx)
}

// Create mocks base method.
func (m *MockGameRepository) Create(ctx context.Context, game *Game) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGameRepositoryMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameRepository)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockGameRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockGameRepository) GetByID(ctx context.Context, id uint) (*Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameRepository)(nil).GetByID), ctx, id)
}

// GetByIDPreloaded mocks base method.
func (m *MockGameRepository) GetByIDPreloaded(ctx context.Context, id uint) (*Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDPreloaded", ctx, id)
	ret0, _ := ret[0].(*Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDPreloaded indicates an expected call of GetByIDPreloaded.
func (mr *MockGameRepositoryMockRecorder) GetByIDPreloaded(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDPreloaded", reflect.TypeOf((*MockGameRepository)(nil).GetByIDPreloaded), ctx, id)
}

// GetFinishedPassingByGameAndTeam mocks base method.
func (m *MockGameRepository) GetFinishedPassingByGameAndTeam(ctx context.Context, gameID, teamID uint) (*GamePassing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFinishedPassingByGameAndTeam", ctx, gameID, teamID)
	ret0, _ := ret[0].(*GamePassing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFinishedPassingByGameAndTeam indicates an expected call of GetFinishedPassingByGameAndTeam.
func (mr *MockGameRepositoryMockRecorder) GetFinishedPassingByGameAndTeam(ctx, gameID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFinishedPassingByGameAndTeam", reflect.TypeOf((*MockGameRepository)(nil).GetFinishedPassingByGameAndTeam), ctx, gameID, teamID)
}

// GetGameSettingByGameID mocks base method.
func (m *MockGameRepository) GetGameSettingByGameID(ctx context.Context, gameID uint) (*GameSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameSettingByGameID", ctx, gameID)
	ret0, _ := ret[0].(*GameSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameSettingByGameID indicates an expected call of GetGameSettingByGameID.
func (mr *MockGameRepositoryMockRecorder) GetGameSettingByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameSettingByGameID", reflect.TypeOf((*MockGameRepository)(nil).GetGameSettingByGameID), ctx, gameID)
}

// GetLogsByGameID mocks base method.
func (m *MockGameRepository) GetLogsByGameID(ctx context.Context, gameID uint) ([]Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogsByGameID", ctx, gameID)
	ret0, _ := ret[0].([]Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogsByGameID indicates an expected call of GetLogsByGameID.
func (mr *MockGameRepositoryMockRecorder) GetLogsByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogsByGameID", reflect.TypeOf((*MockGameRepository)(nil).GetLogsByGameID), ctx, gameID)
}

// GetLogsByGameIDPaginated mocks base method.
func (m *MockGameRepository) GetLogsByGameIDPaginated(ctx context.Context, gameID uint, page, pageSize int) ([]Log, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogsByGameIDPaginated", ctx, gameID, page, pageSize)
	ret0, _ := ret[0].([]Log)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLogsByGameIDPaginated indicates an expected call of GetLogsByGameIDPaginated.
func (mr *MockGameRepositoryMockRecorder) GetLogsByGameIDPaginated(ctx, gameID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogsByGameIDPaginated", reflect.TypeOf((*MockGameRepository)(nil).GetLogsByGameIDPaginated), ctx, gameID, page, pageSize)
}

// GetPassingByUser mocks base method.
func (m *MockGameRepository) GetPassingByUser(ctx context.Context, gameID, userID uint) (*GamePassing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassingByUser", ctx, gameID, userID)
	ret0, _ := ret[0].(*GamePassing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassingByUser indicates an expected call of GetPassingByUser.
func (mr *MockGameRepositoryMockRecorder) GetPassingByUser(ctx, gameID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassingByUser", reflect.TypeOf((*MockGameRepository)(nil).GetPassingByUser), ctx, gameID, userID)
}

// IsTeamCaptain mocks base method.
func (m *MockGameRepository) IsTeamCaptain(ctx context.Context, teamID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTeamCaptain", ctx, teamID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTeamCaptain indicates an expected call of IsTeamCaptain.
func (mr *MockGameRepositoryMockRecorder) IsTeamCaptain(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTeamCaptain", reflect.TypeOf((*MockGameRepository)(nil).IsTeamCaptain), ctx, teamID, userID)
}

// IsTeamMember mocks base method.
func (m *MockGameRepository) IsTeamMember(ctx context.Context, teamID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTeamMember", ctx, teamID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTeamMember indicates an expected call of IsTeamMember.
func (mr *MockGameRepositoryMockRecorder) IsTeamMember(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTeamMember", reflect.TypeOf((*MockGameRepository)(nil).IsTeamMember), ctx, teamID, userID)
}

// ListByDateRange mocks base method.
func (m *MockGameRepository) ListByDateRange(ctx context.Context, from, to time.Time) ([]Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDateRange", ctx, from, to)
	ret0, _ := ret[0].([]Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDateRange indicates an expected call of ListByDateRange.
func (mr *MockGameRepositoryMockRecorder) ListByDateRange(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDateRange", reflect.TypeOf((*MockGameRepository)(nil).ListByDateRange), ctx, from, to)
}

// Model mocks base method.
func (m *MockGameRepository) Model(ctx context.Context) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Model", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Model indicates an expected call of Model.
func (mr *MockGameRepositoryMockRecorder) Model(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Model", reflect.TypeOf((*MockGameRepository)(nil).Model), ctx)
}

// Save mocks base method.
func (m *MockGameRepository) Save(ctx context.Context, game *Game) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, game)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGameRepositoryMockRecorder) Save(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGameRepository)(nil).Save), ctx, game)
}

// Update mocks base method.
func (m *MockGameRepository) Update(ctx context.Context, game *Game) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGameRepositoryMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameRepository)(nil).Update), ctx, game)
}

// UpsertGameSetting mocks base method.
func (m *MockGameRepository) UpsertGameSetting(ctx context.Context, settings *GameSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGameSetting", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertGameSetting indicates an expected call of UpsertGameSetting.
func (mr *MockGameRepositoryMockRecorder) UpsertGameSetting(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGameSetting", reflect.TypeOf((*MockGameRepository)(nil).UpsertGameSetting), ctx, settings)
}

// MockGamePassingRepository is a mock of GamePassingRepository interface.
type MockGamePassingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGamePassingRepositoryMockRecorder
	isgomock struct{}
}

// MockGamePassingRepositoryMockRecorder is the mock recorder for MockGamePassingRepository.
type MockGamePassingRepositoryMockRecorder struct {
	mock *MockGamePassingRepository
}

// NewMockGamePassingRepository creates a new mock instance.
func NewMockGamePassingRepository(ctrl *gomock.Controller) *MockGamePassingRepository {
	mock := &MockGamePassingRepository{ctrl: ctrl}
	mock.recorder = &MockGamePassingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGamePassingRepository) EXPECT() *MockGamePassingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGamePassingRepository) Create(ctx context.Context, passing *GamePassing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, passing)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGamePassingRepositoryMockRecorder) Create(ctx, passing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGamePassingRepository)(nil).Create), ctx, passing)
}

// FindActiveByGame mocks base method.
func (m *MockGamePassingRepository) FindActiveByGame(ctx context.Context, gameID uint) ([]GamePassing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByGame", ctx, gameID)
	ret0, _ := ret[0].([]GamePassing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByGame indicates an expected call of FindActiveByGame.
func (mr *MockGamePassingRepositoryMockRecorder) FindActiveByGame(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByGame", reflect.TypeOf((*MockGamePassingRepository)(nil).FindActiveByGame), ctx, gameID)
}

// FindByGameAndTeam mocks base method.
func (m *MockGamePassingRepository) FindByGameAndTeam(ctx context.Context, gameID, teamID uint) (*GamePassing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameAndTeam", ctx, gameID, teamID)
	ret0, _ := ret[0].(*GamePassing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameAndTeam indicates an expected call of FindByGameAndTeam.
func (mr *MockGamePassingRepositoryMockRecorder) FindByGameAndTeam(ctx, gameID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameAndTeam", reflect.TypeOf((*MockGamePassingRepository)(nil).FindByGameAndTeam), ctx, gameID, teamID)
}

// GetByID mocks base method.
func (m *MockGamePassingRepository) GetByID(ctx context.Context, id uint) (*GamePassing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*GamePassing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGamePassingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGamePassingRepository)(nil).GetByID), ctx, id)
}

// Save mocks base method.
func (m *MockGamePassingRepository) Save(ctx context.Context, passing *GamePassing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, passing)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGamePassingRepositoryMockRecorder) Save(ctx, passing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGamePassingRepository)(nil).Save), ctx, passing)
}

// UpdateStatus mocks base method.
func (m *MockGamePassingRepository) UpdateStatus(ctx context.Context, id uint, status GamePassingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockGamePassingRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockGamePassingRepository)(nil).UpdateStatus), ctx, id, status)
}
