// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_service.go -package=game
//

// Package game is a generated GoMock package.
package game

import (
	context "context"
	team "gengine-0/internal/domain/team"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockGameServiceInterface is a mock of GameServiceInterface interface.
type MockGameServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGameServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockGameServiceInterfaceMockRecorder is the mock recorder for MockGameServiceInterface.
type MockGameServiceInterfaceMockRecorder struct {
	mock *MockGameServiceInterface
}

// NewMockGameServiceInterface creates a new mock instance.
func NewMockGameServiceInterface(ctrl *gomock.Controller) *MockGameServiceInterface {
	mock := &MockGameServiceInterface{ctrl: ctrl}
	mock.recorder = &MockGameServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameServiceInterface) EXPECT() *MockGameServiceInterfaceMockRecorder {
	return m.recorder
}

// AutocompleteSearch mocks base method.
func (m *MockGameServiceInterface) AutocompleteSearch(ctx context.Context, query string, limit int) ([]AutocompleteItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutocompleteSearch", ctx, query, limit)
	ret0, _ := ret[0].([]AutocompleteItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutocompleteSearch indicates an expected call of AutocompleteSearch.
func (mr *MockGameServiceInterfaceMockRecorder) AutocompleteSearch(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutocompleteSearch", reflect.TypeOf((*MockGameServiceInterface)(nil).AutocompleteSearch), ctx, query, limit)
}

// CountGamesByAuthor mocks base method.
func (m *MockGameServiceInterface) CountGamesByAuthor(ctx context.Context, authorID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountGamesByAuthor", ctx, authorID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountGamesByAuthor indicates an expected call of CountGamesByAuthor.
func (mr *MockGameServiceInterfaceMockRecorder) CountGamesByAuthor(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountGamesByAuthor", reflect.TypeOf((*MockGameServiceInterface)(nil).CountGamesByAuthor), ctx, authorID)
}

// CreateGameWithCover mocks base method.
func (m *MockGameServiceInterface) CreateGameWithCover(ctx context.Context, dto *CreateGameDTO, authorID uint) (*Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGameWithCover", ctx, dto, authorID)
	ret0, _ := ret[0].(*Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGameWithCover indicates an expected call of CreateGameWithCover.
func (mr *MockGameServiceInterfaceMockRecorder) CreateGameWithCover(ctx, dto, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGameWithCover", reflect.TypeOf((*MockGameServiceInterface)(nil).CreateGameWithCover), ctx, dto, authorID)
}

// Delete mocks base method.
func (m *MockGameServiceInterface) Delete(ctx context.Context, id, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameServiceInterfaceMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameServiceInterface)(nil).Delete), ctx, id, userID)
}

// GetAverageRating mocks base method.
func (m *MockGameServiceInterface) GetAverageRating(ctx context.Context, gameID uint) (float64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageRating", ctx, gameID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAverageRating indicates an expected call of GetAverageRating.
func (mr *MockGameServiceInterfaceMockRecorder) GetAverageRating(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRating", reflect.TypeOf((*MockGameServiceInterface)(nil).GetAverageRating), ctx, gameID)
}

// GetByID mocks base method.
func (m *MockGameServiceInterface) GetByID(ctx context.Context, id, userID uint, isAdmin bool) (*Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID, isAdmin)
	ret0, _ := ret[0].(*Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameServiceInterfaceMockRecorder) GetByID(ctx, id, userID, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameServiceInterface)(nil).GetByID), ctx, id, userID, isAdmin)
}

// GetSettingsWithDefaults mocks base method.
func (m *MockGameServiceInterface) GetSettingsWithDefaults(ctx context.Context, gameID uint) (*GameSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingsWithDefaults", ctx, gameID)
	ret0, _ := ret[0].(*GameSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingsWithDefaults indicates an expected call of GetSettingsWithDefaults.
func (mr *MockGameServiceInterfaceMockRecorder) GetSettingsWithDefaults(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingsWithDefaults", reflect.TypeOf((*MockGameServiceInterface)(nil).GetSettingsWithDefaults), ctx, gameID)
}

// GetUserGamesView mocks base method.
func (m *MockGameServiceInterface) GetUserGamesView(ctx context.Context, userID uint) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGamesView", ctx, userID)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserGamesView indicates an expected call of GetUserGamesView.
func (mr *MockGameServiceInterfaceMockRecorder) GetUserGamesView(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGamesView", reflect.TypeOf((*MockGameServiceInterface)(nil).GetUserGamesView), ctx, userID)
}

// IsUserManager mocks base method.
func (m *MockGameServiceInterface) IsUserManager(ctx context.Context, gameID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserManager", ctx, gameID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserManager indicates an expected call of IsUserManager.
func (mr *MockGameServiceInterfaceMockRecorder) IsUserManager(ctx, gameID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserManager", reflect.TypeOf((*MockGameServiceInterface)(nil).IsUserManager), ctx, gameID, userID)
}

// ListFilteredPaginated mocks base method.
func (m *MockGameServiceInterface) ListFilteredPaginated(ctx context.Context, filter GameFilter, sort *GameSort, page, perPage int) ([]Game, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilteredPaginated", ctx, filter, sort, page, perPage)
	ret0, _ := ret[0].([]Game)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFilteredPaginated indicates an expected call of ListFilteredPaginated.
func (mr *MockGameServiceInterfaceMockRecorder) ListFilteredPaginated(ctx, filter, sort, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilteredPaginated", reflect.TypeOf((*MockGameServiceInterface)(nil).ListFilteredPaginated), ctx, filter, sort, page, perPage)
}

// ListReviews mocks base method.
func (m *MockGameServiceInterface) ListReviews(ctx context.Context, gameID uint) ([]Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviews", ctx, gameID)
	ret0, _ := ret[0].([]Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReviews indicates an expected call of ListReviews.
func (mr *MockGameServiceInterfaceMockRecorder) ListReviews(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviews", reflect.TypeOf((*MockGameServiceInterface)(nil).ListReviews), ctx, gameID)
}

// Publish mocks base method.
func (m *MockGameServiceInterface) Publish(ctx context.Context, id, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockGameServiceInterfaceMockRecorder) Publish(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGameServiceInterface)(nil).Publish), ctx, id, userID)
}

// SaveSettings mocks base method.
func (m *MockGameServiceInterface) SaveSettings(ctx context.Context, gameID uint, settings GameSetting) (*GameSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSettings", ctx, gameID, settings)
	ret0, _ := ret[0].(*GameSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSettings indicates an expected call of SaveSettings.
func (mr *MockGameServiceInterfaceMockRecorder) SaveSettings(ctx, gameID, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSettings", reflect.TypeOf((*MockGameServiceInterface)(nil).SaveSettings), ctx, gameID, settings)
}

// ShowGame mocks base method.
func (m *MockGameServiceInterface) ShowGame(ctx context.Context, gameID, viewerID uint, isAdmin bool) (*Game, []Review, float64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowGame", ctx, gameID, viewerID, isAdmin)
	ret0, _ := ret[0].(*Game)
	ret1, _ := ret[1].([]Review)
	ret2, _ := ret[2].(float64)
	ret3, _ := ret[3].(int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// ShowGame indicates an expected call of ShowGame.
func (mr *MockGameServiceInterfaceMockRecorder) ShowGame(ctx, gameID, viewerID, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowGame", reflect.TypeOf((*MockGameServiceInterface)(nil).ShowGame), ctx, gameID, viewerID, isAdmin)
}

// UpdateGameWithCover mocks base method.
func (m *MockGameServiceInterface) UpdateGameWithCover(ctx context.Context, gameID uint, dto *UpdateGameDTO, userID uint, isAdmin bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGameWithCover", ctx, gameID, dto, userID, isAdmin)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGameWithCover indicates an expected call of UpdateGameWithCover.
func (mr *MockGameServiceInterfaceMockRecorder) UpdateGameWithCover(ctx, gameID, dto, userID, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGameWithCover", reflect.TypeOf((*MockGameServiceInterface)(nil).UpdateGameWithCover), ctx, gameID, dto, userID, isAdmin)
}

// MockCoAuthorServiceInterface is a mock of CoAuthorServiceInterface interface.
type MockCoAuthorServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCoAuthorServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockCoAuthorServiceInterfaceMockRecorder is the mock recorder for MockCoAuthorServiceInterface.
type MockCoAuthorServiceInterfaceMockRecorder struct {
	mock *MockCoAuthorServiceInterface
}

// NewMockCoAuthorServiceInterface creates a new mock instance.
func NewMockCoAuthorServiceInterface(ctrl *gomock.Controller) *MockCoAuthorServiceInterface {
	mock := &MockCoAuthorServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCoAuthorServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoAuthorServiceInterface) EXPECT() *MockCoAuthorServiceInterfaceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCoAuthorServiceInterface) Add(ctx context.Context, gameID, newCoAuthorID, ownerID uint, role string, permissions []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, gameID, newCoAuthorID, ownerID, role, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCoAuthorServiceInterfaceMockRecorder) Add(ctx, gameID, newCoAuthorID, ownerID, role, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCoAuthorServiceInterface)(nil).Add), ctx, gameID, newCoAuthorID, ownerID, role, permissions)
}

// CanEditContent mocks base method.
func (m *MockCoAuthorServiceInterface) CanEditContent(ctx context.Context, gameID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanEditContent", ctx, gameID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanEditContent indicates an expected call of CanEditContent.
func (mr *MockCoAuthorServiceInterfaceMockRecorder) CanEditContent(ctx, gameID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanEditContent", reflect.TypeOf((*MockCoAuthorServiceInterface)(nil).CanEditContent), ctx, gameID, userID)
}

// CanModerateGame mocks base method.
func (m *MockCoAuthorServiceInterface) CanModerateGame(ctx context.Context, gameID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanModerateGame", ctx, gameID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanModerateGame indicates an expected call of CanModerateGame.
func (mr *MockCoAuthorServiceInterfaceMockRecorder) CanModerateGame(ctx, gameID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanModerateGame", reflect.TypeOf((*MockCoAuthorServiceInterface)(nil).CanModerateGame), ctx, gameID, userID)
}

// CanUploadMedia mocks base method.
func (m *MockCoAuthorServiceInterface) CanUploadMedia(ctx context.Context, gameID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanUploadMedia", ctx, gameID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanUploadMedia indicates an expected call of CanUploadMedia.
func (mr *MockCoAuthorServiceInterfaceMockRecorder) CanUploadMedia(ctx, gameID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanUploadMedia", reflect.TypeOf((*MockCoAuthorServiceInterface)(nil).CanUploadMedia), ctx, gameID, userID)
}

// HasPermission mocks base method.
func (m *MockCoAuthorServiceInterface) HasPermission(ctx context.Context, gameID, userID uint, requiredRole string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermission", ctx, gameID, userID, requiredRole)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockCoAuthorServiceInterfaceMockRecorder) HasPermission(ctx, gameID, userID, requiredRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockCoAuthorServiceInterface)(nil).HasPermission), ctx, gameID, userID, requiredRole)
}

// IsUserManager mocks base method.
func (m *MockCoAuthorServiceInterface) IsUserManager(ctx context.Context, gameID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserManager", ctx, gameID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserManager indicates an expected call of IsUserManager.
func (mr *MockCoAuthorServiceInterfaceMockRecorder) IsUserManager(ctx, gameID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserManager", reflect.TypeOf((*MockCoAuthorServiceInterface)(nil).IsUserManager), ctx, gameID, userID)
}

// List mocks base method.
func (m *MockCoAuthorServiceInterface) List(ctx context.Context, gameID uint) ([]CoAuthor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, gameID)
	ret0, _ := ret[0].([]CoAuthor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCoAuthorServiceInterfaceMockRecorder) List(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCoAuthorServiceInterface)(nil).List), ctx, gameID)
}

// Remove mocks base method.
func (m *MockCoAuthorServiceInterface) Remove(ctx context.Context, gameID, coAuthorUserID, ownerID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, gameID, coAuthorUserID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockCoAuthorServiceInterfaceMockRecorder) Remove(ctx, gameID, coAuthorUserID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockCoAuthorServiceInterface)(nil).Remove), ctx, gameID, coAuthorUserID, ownerID)
}

// MockAuditServiceInterface is a mock of AuditServiceInterface interface.
type MockAuditServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAuditServiceInterfaceMockRecorder is the mock recorder for MockAuditServiceInterface.
type MockAuditServiceInterfaceMockRecorder struct {
	mock *MockAuditServiceInterface
}

// NewMockAuditServiceInterface creates a new mock instance.
func NewMockAuditServiceInterface(ctrl *gomock.Controller) *MockAuditServiceInterface {
	mock := &MockAuditServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuditServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditServiceInterface) EXPECT() *MockAuditServiceInterfaceMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockAuditServiceInterface) Log(userID uint, action, objectType string, objectID uint, details string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", userID, action, objectType, objectID, details)
}

// Log indicates an expected call of Log.
func (mr *MockAuditServiceInterfaceMockRecorder) Log(userID, action, objectType, objectID, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockAuditServiceInterface)(nil).Log), userID, action, objectType, objectID, details)
}

// MockGamePassingServiceInterface is a mock of GamePassingServiceInterface interface.
type MockGamePassingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGamePassingServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockGamePassingServiceInterfaceMockRecorder is the mock recorder for MockGamePassingServiceInterface.
type MockGamePassingServiceInterfaceMockRecorder struct {
	mock *MockGamePassingServiceInterface
}

// NewMockGamePassingServiceInterface creates a new mock instance.
func NewMockGamePassingServiceInterface(ctrl *gomock.Controller) *MockGamePassingServiceInterface {
	mock := &MockGamePassingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockGamePassingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGamePassingServiceInterface) EXPECT() *MockGamePassingServiceInterfaceMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockGamePassingServiceInterface) Apply(ctx context.Context, gameID, teamID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, gameID, teamID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockGamePassingServiceInterfaceMockRecorder) Apply(ctx, gameID, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).Apply), ctx, gameID, teamID, userID)
}

// GetAttemptsPerUser mocks base method.
func (m *MockGamePassingServiceInterface) GetAttemptsPerUser(ctx context.Context, gameID uint) ([]AttemptPerUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttemptsPerUser", ctx, gameID)
	ret0, _ := ret[0].([]AttemptPerUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttemptsPerUser indicates an expected call of GetAttemptsPerUser.
func (mr *MockGamePassingServiceInterfaceMockRecorder) GetAttemptsPerUser(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttemptsPerUser", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).GetAttemptsPerUser), ctx, gameID)
}

// GetTeamAnswer mocks base method.
func (m *MockGamePassingServiceInterface) GetTeamAnswer(ctx context.Context, levelID, teamID uint) (*LevelTeamAnswer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamAnswer", ctx, levelID, teamID)
	ret0, _ := ret[0].(*LevelTeamAnswer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamAnswer indicates an expected call of GetTeamAnswer.
func (mr *MockGamePassingServiceInterfaceMockRecorder) GetTeamAnswer(ctx, levelID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamAnswer", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).GetTeamAnswer), ctx, levelID, teamID)
}

// GetTeamRoute mocks base method.
func (m *MockGamePassingServiceInterface) GetTeamRoute(ctx context.Context, passingID uint) ([]GamePassingLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamRoute", ctx, passingID)
	ret0, _ := ret[0].([]GamePassingLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamRoute indicates an expected call of GetTeamRoute.
func (mr *MockGamePassingServiceInterfaceMockRecorder) GetTeamRoute(ctx, passingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamRoute", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).GetTeamRoute), ctx, passingID)
}

// GetTeamsByCaptain mocks base method.
func (m *MockGamePassingServiceInterface) GetTeamsByCaptain(ctx context.Context, userID uint) ([]team.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamsByCaptain", ctx, userID)
	ret0, _ := ret[0].([]team.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamsByCaptain indicates an expected call of GetTeamsByCaptain.
func (mr *MockGamePassingServiceInterfaceMockRecorder) GetTeamsByCaptain(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamsByCaptain", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).GetTeamsByCaptain), ctx, userID)
}

// ListByGamePaginated mocks base method.
func (m *MockGamePassingServiceInterface) ListByGamePaginated(ctx context.Context, gameID uint, page, perPage int) ([]GamePassing, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGamePaginated", ctx, gameID, page, perPage)
	ret0, _ := ret[0].([]GamePassing)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByGamePaginated indicates an expected call of ListByGamePaginated.
func (mr *MockGamePassingServiceInterfaceMockRecorder) ListByGamePaginated(ctx, gameID, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGamePaginated", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).ListByGamePaginated), ctx, gameID, page, perPage)
}

// ListTestPassings mocks base method.
func (m *MockGamePassingServiceInterface) ListTestPassings(ctx context.Context, gameID uint, result *[]GamePassing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTestPassings", ctx, gameID, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListTestPassings indicates an expected call of ListTestPassings.
func (mr *MockGamePassingServiceInterfaceMockRecorder) ListTestPassings(ctx, gameID, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTestPassings", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).ListTestPassings), ctx, gameID, result)
}

// SetTeamAnswer mocks base method.
func (m *MockGamePassingServiceInterface) SetTeamAnswer(ctx context.Context, gameID, levelID, teamID uint, code, hint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTeamAnswer", ctx, gameID, levelID, teamID, code, hint)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTeamAnswer indicates an expected call of SetTeamAnswer.
func (mr *MockGamePassingServiceInterfaceMockRecorder) SetTeamAnswer(ctx, gameID, levelID, teamID, code, hint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTeamAnswer", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).SetTeamAnswer), ctx, gameID, levelID, teamID, code, hint)
}

// SetTeamRoute mocks base method.
func (m *MockGamePassingServiceInterface) SetTeamRoute(ctx context.Context, gameID, passingID uint, levelIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTeamRoute", ctx, gameID, passingID, levelIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTeamRoute indicates an expected call of SetTeamRoute.
func (mr *MockGamePassingServiceInterfaceMockRecorder) SetTeamRoute(ctx, gameID, passingID, levelIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTeamRoute", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).SetTeamRoute), ctx, gameID, passingID, levelIDs)
}

// SetTeamStartTime mocks base method.
func (m *MockGamePassingServiceInterface) SetTeamStartTime(ctx context.Context, gameID, passingID uint, startTime *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTeamStartTime", ctx, gameID, passingID, startTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTeamStartTime indicates an expected call of SetTeamStartTime.
func (mr *MockGamePassingServiceInterfaceMockRecorder) SetTeamStartTime(ctx, gameID, passingID, startTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTeamStartTime", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).SetTeamStartTime), ctx, gameID, passingID, startTime)
}

// StartGame mocks base method.
func (m *MockGamePassingServiceInterface) StartGame(ctx context.Context, passingID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartGame", ctx, passingID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartGame indicates an expected call of StartGame.
func (mr *MockGamePassingServiceInterfaceMockRecorder) StartGame(ctx, passingID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGame", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).StartGame), ctx, passingID, userID)
}

// UpdateStatus mocks base method.
func (m *MockGamePassingServiceInterface) UpdateStatus(ctx context.Context, passingID uint, status GamePassingStatus, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, passingID, status, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockGamePassingServiceInterfaceMockRecorder) UpdateStatus(ctx, passingID, status, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockGamePassingServiceInterface)(nil).UpdateStatus), ctx, passingID, status, userID)
}

// MockGamePlayServiceInterface is a mock of GamePlayServiceInterface interface.
type MockGamePlayServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGamePlayServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockGamePlayServiceInterfaceMockRecorder is the mock recorder for MockGamePlayServiceInterface.
type MockGamePlayServiceInterfaceMockRecorder struct {
	mock *MockGamePlayServiceInterface
}

// NewMockGamePlayServiceInterface creates a new mock instance.
func NewMockGamePlayServiceInterface(ctrl *gomock.Controller) *MockGamePlayServiceInterface {
	mock := &MockGamePlayServiceInterface{ctrl: ctrl}
	mock.recorder = &MockGamePlayServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGamePlayServiceInterface) EXPECT() *MockGamePlayServiceInterfaceMockRecorder {
	return m.recorder
}

// AcceptBlackboxAnswer mocks base method.
func (m *MockGamePlayServiceInterface) AcceptBlackboxAnswer(ctx context.Context, passingID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptBlackboxAnswer", ctx, passingID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptBlackboxAnswer indicates an expected call of AcceptBlackboxAnswer.
func (mr *MockGamePlayServiceInterfaceMockRecorder) AcceptBlackboxAnswer(ctx, passingID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptBlackboxAnswer", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).AcceptBlackboxAnswer), ctx, passingID, userID)
}

// GetGameplayData mocks base method.
func (m *MockGamePlayServiceInterface) GetGameplayData(ctx context.Context, passingID uint) (*GameplayData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameplayData", ctx, passingID)
	ret0, _ := ret[0].(*GameplayData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameplayData indicates an expected call of GetGameplayData.
func (mr *MockGamePlayServiceInterfaceMockRecorder) GetGameplayData(ctx, passingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameplayData", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).GetGameplayData), ctx, passingID)
}

// GetPassingWithGame mocks base method.
func (m *MockGamePlayServiceInterface) GetPassingWithGame(ctx context.Context, passingID uint) (*GamePassing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassingWithGame", ctx, passingID)
	ret0, _ := ret[0].(*GamePassing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassingWithGame indicates an expected call of GetPassingWithGame.
func (mr *MockGamePlayServiceInterfaceMockRecorder) GetPassingWithGame(ctx, passingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassingWithGame", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).GetPassingWithGame), ctx, passingID)
}

// IsTeamMember mocks base method.
func (m *MockGamePlayServiceInterface) IsTeamMember(ctx context.Context, teamID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTeamMember", ctx, teamID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTeamMember indicates an expected call of IsTeamMember.
func (mr *MockGamePlayServiceInterfaceMockRecorder) IsTeamMember(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTeamMember", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).IsTeamMember), ctx, teamID, userID)
}

// SkipLevelTest mocks base method.
func (m *MockGamePlayServiceInterface) SkipLevelTest(ctx context.Context, passingID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkipLevelTest", ctx, passingID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SkipLevelTest indicates an expected call of SkipLevelTest.
func (mr *MockGamePlayServiceInterfaceMockRecorder) SkipLevelTest(ctx, passingID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkipLevelTest", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).SkipLevelTest), ctx, passingID, userID)
}

// StartTesting mocks base method.
func (m *MockGamePlayServiceInterface) StartTesting(ctx context.Context, gameID, userID uint) (*GamePassing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTesting", ctx, gameID, userID)
	ret0, _ := ret[0].(*GamePassing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTesting indicates an expected call of StartTesting.
func (mr *MockGamePlayServiceInterfaceMockRecorder) StartTesting(ctx, gameID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTesting", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).StartTesting), ctx, gameID, userID)
}

// SubmitCode mocks base method.
func (m *MockGamePlayServiceInterface) SubmitCode(ctx context.Context, passingID, userID uint, code string) (*SubmitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitCode", ctx, passingID, userID, code)
	ret0, _ := ret[0].(*SubmitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitCode indicates an expected call of SubmitCode.
func (mr *MockGamePlayServiceInterfaceMockRecorder) SubmitCode(ctx, passingID, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitCode", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).SubmitCode), ctx, passingID, userID, code)
}

// SubmitFile mocks base method.
func (m *MockGamePlayServiceInterface) SubmitFile(ctx context.Context, passingID, userID uint, filePath string) (*Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitFile", ctx, passingID, userID, filePath)
	ret0, _ := ret[0].(*Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitFile indicates an expected call of SubmitFile.
func (mr *MockGamePlayServiceInterfaceMockRecorder) SubmitFile(ctx, passingID, userID, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitFile", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).SubmitFile), ctx, passingID, userID, filePath)
}

// SubmitTestCode mocks base method.
func (m *MockGamePlayServiceInterface) SubmitTestCode(ctx context.Context, passingID, userID uint, code string) (*Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitTestCode", ctx, passingID, userID, code)
	ret0, _ := ret[0].(*Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitTestCode indicates an expected call of SubmitTestCode.
func (mr *MockGamePlayServiceInterfaceMockRecorder) SubmitTestCode(ctx, passingID, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitTestCode", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).SubmitTestCode), ctx, passingID, userID, code)
}

// UseHint mocks base method.
func (m *MockGamePlayServiceInterface) UseHint(ctx context.Context, passingID, userID uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseHint", ctx, passingID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UseHint indicates an expected call of UseHint.
func (mr *MockGamePlayServiceInterfaceMockRecorder) UseHint(ctx, passingID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseHint", reflect.TypeOf((*MockGamePlayServiceInterface)(nil).UseHint), ctx, passingID, userID)
}

// MockGameAdminServiceInterface is a mock of GameAdminServiceInterface interface.
type MockGameAdminServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGameAdminServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockGameAdminServiceInterfaceMockRecorder is the mock recorder for MockGameAdminServiceInterface.
type MockGameAdminServiceInterfaceMockRecorder struct {
	mock *MockGameAdminServiceInterface
}

// NewMockGameAdminServiceInterface creates a new mock instance.
func NewMockGameAdminServiceInterface(ctrl *gomock.Controller) *MockGameAdminServiceInterface {
	mock := &MockGameAdminServiceInterface{ctrl: ctrl}
	mock.recorder = &MockGameAdminServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameAdminServiceInterface) EXPECT() *MockGameAdminServiceInterfaceMockRecorder {
	return m.recorder
}

// DeleteLevelFromActiveGame mocks base method.
func (m *MockGameAdminServiceInterface) DeleteLevelFromActiveGame(ctx context.Context, gameID, levelID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLevelFromActiveGame", ctx, gameID, levelID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLevelFromActiveGame indicates an expected call of DeleteLevelFromActiveGame.
func (mr *MockGameAdminServiceInterfaceMockRecorder) DeleteLevelFromActiveGame(ctx, gameID, levelID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLevelFromActiveGame", reflect.TypeOf((*MockGameAdminServiceInterface)(nil).DeleteLevelFromActiveGame), ctx, gameID, levelID, userID)
}

// DisqualifyTeam mocks base method.
func (m *MockGameAdminServiceInterface) DisqualifyTeam(ctx context.Context, gameID, teamID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisqualifyTeam", ctx, gameID, teamID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisqualifyTeam indicates an expected call of DisqualifyTeam.
func (mr *MockGameAdminServiceInterfaceMockRecorder) DisqualifyTeam(ctx, gameID, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisqualifyTeam", reflect.TypeOf((*MockGameAdminServiceInterface)(nil).DisqualifyTeam), ctx, gameID, teamID, userID)
}

// ForceFinishGame mocks base method.
func (m *MockGameAdminServiceInterface) ForceFinishGame(ctx context.Context, gameID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceFinishGame", ctx, gameID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceFinishGame indicates an expected call of ForceFinishGame.
func (mr *MockGameAdminServiceInterfaceMockRecorder) ForceFinishGame(ctx, gameID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceFinishGame", reflect.TypeOf((*MockGameAdminServiceInterface)(nil).ForceFinishGame), ctx, gameID, userID)
}
