// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service.go -package=level
//

// Package level is a generated GoMock package.
package level

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActiveGameManager is a mock of ActiveGameManager interface.
type MockActiveGameManager struct {
	ctrl     *gomock.Controller
	recorder *MockActiveGameManagerMockRecorder
	isgomock struct{}
}

// MockActiveGameManagerMockRecorder is the mock recorder for MockActiveGameManager.
type MockActiveGameManagerMockRecorder struct {
	mock *MockActiveGameManager
}

// NewMockActiveGameManager creates a new mock instance.
func NewMockActiveGameManager(ctrl *gomock.Controller) *MockActiveGameManager {
	mock := &MockActiveGameManager{ctrl: ctrl}
	mock.recorder = &MockActiveGameManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActiveGameManager) EXPECT() *MockActiveGameManagerMockRecorder {
	return m.recorder
}

// DeleteLevelFromActiveGame mocks base method.
func (m *MockActiveGameManager) DeleteLevelFromActiveGame(ctx context.Context, gameID, levelID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLevelFromActiveGame", ctx, gameID, levelID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLevelFromActiveGame indicates an expected call of DeleteLevelFromActiveGame.
func (mr *MockActiveGameManagerMockRecorder) DeleteLevelFromActiveGame(ctx, gameID, levelID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLevelFromActiveGame", reflect.TypeOf((*MockActiveGameManager)(nil).DeleteLevelFromActiveGame), ctx, gameID, levelID, userID)
}
