basePath: /
host: localhost:8080
info:
  contact:
    email: support@gengine.io
    name: API Support
  description: API для платформы квестов Gengine
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Gengine API
  version: "1.0"
paths: {}
securityDefinitions:
  JWT:
    in: cookie
    name: jwt
    type: apiKey
swagger: "2.0"
